name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - '.github/workflows/docker-image.yml'
      - 'github-actions/Docker/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: 
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/gcp-devops:latest
      working-directory: github-actions/Docker

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/gcp-devops:latest
      working-directory: github-actions/Docker