name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths: 
      - '.github/workflows/docker-image.yml'
      - 'github-actions/Docker/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: 
        docker build . --file Dockerfile --tag hello-world-python-app:$(date +%s)
      working-directory: github-actions/Docker

  publish-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Docker image
      run:
        docker push babarali07/gcp-devops:latest
      working-directory: github-actions/Docker